using Microsoft.CodeAnalysis;

namespace JOS.Enumeration.SourceGenerator;

[Generator]
internal class ImplicitOperatorsSourceGenerator : ISourceGenerator
{
    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForSyntaxNotifications(() => new EnumerationReceiver());
    }

    public void Execute(GeneratorExecutionContext context)
    {
        if (context.SyntaxContextReceiver is not EnumerationReceiver receiver)
        {
            return;
        }

        var enumerations = receiver.EnumerationImplementations;

        foreach (var enumeration in enumerations)
        {
            context.CancellationToken.ThrowIfCancellationRequested();
            var visibility = enumeration.DeclaredAccessibility.ToLowerString();
            var source = $$"""
            // <auto-generated>
            //     This code was auto generated by JOS.Enumeration.SourceGenerator
            // </auto-generated>

            using JOS.Enumeration;

            namespace {{enumeration.ContainingNamespace}};

            {{visibility}} partial record {{enumeration.MetadataName}} : Enumeration<{{enumeration.MetadataName}}>
            {
                public static implicit operator int({{enumeration.MetadataName}} item) => item.Value;
                public static implicit operator {{enumeration.MetadataName}}(int value) => FromValue(value);
            }
            """;

            context.AddSource($"{enumeration.MetadataName}.Generated.Implicit.cs", source);
        }
    }
}
