name: Verify

on:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    timeout-minutes: 10
    name: Build and Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: jos
          POSTGRES_PASSWORD: any
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Fetch main
        run: |
          git fetch origin main &&
          git checkout -b main origin/main
          git checkout -
      - uses: dotnet/nbgv@master
        id: nbgv
      - name: Skip if bot
        run: |
          AUTHOR=$(git log -1 --pretty=%an)
          if [ "$AUTHOR" == "jos-yoda" ]; then
            echo "Commit made by bot, skipping further steps in the pipeline."
            exit 0
          fi
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x
      - name: Build Version ${{ steps.nbgv.outputs.nugetpackageversion }}
        run: dotnet build -c Release
      - name: Check formatting
        continue-on-error: true
        id: checkFormatting
        run: | 
          dotnet format whitespace --no-restore --verify-no-changes --include $(git diff --name-only HEAD origin/main | tr '\n' ' ')
          dotnet format style --no-restore --verify-no-changes --include $(git diff --name-only HEAD origin/main | tr '\n' ' ')
      - name: Fix formatting
        continue-on-error: true
        if: steps.checkFormatting.outcome == 'failure'
        run: |
          dotnet format whitespace --no-restore --include $(git diff --name-only HEAD origin/main | tr '\n' ' ')
          dotnet format style --no-restore --include $(git diff --name-only HEAD origin/main | tr '\n' ' ')
      - name: Test Version ${{ steps.nbgv.outputs.nugetpackageversion }} - .NET 8
        run: dotnet test -c Release --no-build --no-restore --framework net8.0
      - name: Test Version ${{ steps.nbgv.outputs.nugetpackageversion }} - .NET 9
        run: dotnet test -c Release --no-build --no-restore --framework net9.0
      - name: Test Version ${{ steps.nbgv.outputs.nugetpackageversion }} - .NET 10
        run: dotnet test -c Release --no-build --no-restore --framework net10.0
      - name: Push formatting fixes
        if: steps.checkFormatting.outcome == 'failure'
        run: |
          git config user.name "jos-yoda" &&
          git config user.email "144553819+jos-yoda@users.noreply.github.com" &&
          git commit -am "Fixes formatting - ${{steps.nbgv.outputs.nugetpackageversion}}" &&
          git push origin HEAD:${{github.event.pull_request.head.ref}}
        env:
          GITHUB_TOKEN: ${{ secrets.JOS_YODA_PAT }}
      - name: Pack JOS.Enumeration.sln ${{ steps.nbgv.outputs.nugetpackageversion }}
        run: dotnet pack JOS.Enumeration.sln -c Release -o ./nuget-packages --no-build
      - name: Store nuget packages as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: "nuget-packages/"
