name: Verify

on:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    timeout-minutes: 10
    name: Build and Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: jos
          POSTGRES_PASSWORD: any
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: dotnet/nbgv@master
      id: nbgv
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.x
    - name: Test Version ${{ steps.nbgv.outputs.nugetpackageversion }}
      run: dotnet test -c Release
    - name: Pack JOS.Enumeration.sln ${{ steps.nbgv.outputs.nugetpackageversion }}
      run: dotnet pack JOS.Enumeration.sln -c Release -o ./nuget-packages --no-build
    - name: Store nuget packages as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages
        path: "nuget-packages/"
